"""Add refresh_tokens, api_keys tables and api_key_id to kpi_records 

Revision ID: ab2a600be900
Revises: e1d34a81b65c
Create Date: 2026-07-28 15:48:19.744667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab2a600be900'
down_revision: Union[str, Sequence[str], None] = 'e1d34a81b65c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
