"""add created_by to projects

Revision ID: cd642f1f2f55
Revises: 5ba55f3e2624
Create Date: 2026-07-27 14:30:03.794594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd642f1f2f55'
down_revision: Union[str, Sequence[str], None] = '5ba55f3e2624'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('created_by', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'projects', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'created_by')
    # ### end Alembic commands ###
